name: mock_mdx_network
description: Mock Network Library
version: 0.0.1
homepage: 'https://mortydex.com'

publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  mdx_network:
    path: ../mdx_network
  mockito: ^5.4.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.4
  lint: ^2.1.2
  test: ^1.24.3