name: mdx_core
description: MortyDex Core Library
version: 0.0.1
homepage: "https://mortydex.com"

publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1