name: mdx_characters
description: Characters Module
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  mdx_core:
    path: ../../packages/mdx_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
