// Mocks generated by Mockito 5.4.1 from annotations
// in mdx_logger/test/mdx_logger_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mdx_logger/mdx_logger.dart' as _i3;
import 'package:mdx_logger/providers/console_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ConsoleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsoleProvider extends _i1.Mock implements _i2.ConsoleProvider {
  @override
  void call({
    required String? message,
    required _i3.LogTypes? type,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #message: message,
            #type: type,
          },
        ),
        returnValueForMissingStub: null,
      );
}
