name: mdx_dicontainer
description: Dependency Injection Container Library
version: 0.0.1
homepage: 'https://mortydex.com'

publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.4
  lint: ^2.1.2
  mockito: ^5.4.1
  test: ^1.24.3
